CREATE DATABASE BUILD;


CREATE TABLE TB_ARCHITECT
(
   ID INT PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR (50),
   IMAGE_PATH VARCHAR (50),
   REMARKS VARCHAR (2000),
   TYPE VARCHAR (30),
   CREATE_DATE DATE,
   STATUS VARCHAR (30) default 1
);

